env:
  name: [Asterix, Breakout, Enduro, Seaquest, MsPacman, SpaceInvaders]

estimator:
  encoder:
    args_:
      root:
        - results/2022Sep12-213046_6g_OR_wm/0000_model.reward_model.args_.layers___/0/
      ckpt_idx: [5_503_126]
      with_logvar: [no]
  qval_net:
    args_:
      fc_layers:
        - [512]
      cn_layers:
        - [[64, 3, 1], [64, 3, 1]]
      inp_ch: [4]  # 2x when with_logvar
