experiment: BYOL

epochs: 10
device: cuda


alpha: 0.99

# divided by seq_steps gives the save freq
base_save_freq: 1_200_000

encoder:
  name: ImpalaEncoder
  args_:
    inp_ch: 1
    grp_norm: 0
    stack_sz: 1

dynamics_net:
  name: WorldModel
  args_:
    K: 2
    M: 256
    N: 512
    pfx_steps: 20
    seq_steps: 60
    act_no: 18
    act_emb_sz: 32
    act_emb_train: no

optim:
  name: Adam
  args_:
    lr: 0.0001
    # betas: [0.5, 0.9]


dset:
  path: ./fold0/{asterix,breakout,enduro,mspacman,seaquest,spaceinvaders}_{0000..0165}.tar
  shuffle: 8000
  batch_size: 2
  subsample: 3  # sample `subsample` times from a window

loader:
  args_:
    batch_size: null
    num_workers: 12
    pin_memory: true
  shuffle: 1000
  batch_size: 32
